setwd("C:/Users/Kanupriya/Desktop/Directory")
data <- read.table("C:/Users/Kanupriya/Desktop/Directory/household_power_consumption.txt",header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
HH <- data[data$Date %in% c("1/2/2007","2/2/2007") ,]
gap<- as.numeric(HH$Global_active_power)
sm1 <- as.numeric(HH$Sub_metering_1)
sm2 <- as.numeric(HH$Sub_metering_2)
sm3 <- as.numeric(HH$Sub_metering_3)
dt <- strptime(paste(HH$Date,HH$Time,sep= " "),"%d/%m/%Y %H:%M:%S")
png("plot3.png", width=480, height=480)
plot(dt,sm1,type= "l", xlab=" ",ylab ="Energy Submetering")
lines(dt,sm2,type="l",col= "red")
lines(dt,sm3,type="l",col= "blue")
legend("topright",c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lty=1,lwd=2,col= c("black", "red", "blue"))
dev.off()